import 'dart:io';
import 'package:ffmpeg_kit_flutter_new/ffmpeg_kit.dart';
import 'package:ffmpeg_kit_flutter_new/return_code.dart';
import 'package:path_provider/path_provider.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import '../models/video_source.dart';
import 'whisper_service.dart';

class YouTubeService {
  final YoutubeExplode _yt = YoutubeExplode();

  /// Fetches video details from a YouTube URL or Video ID
  Future<VideoSource> fetchVideoInfo(String urlOrId) async {
    try {
      final parsedId = VideoId.parseVideoId(urlOrId.trim());
      final videoId = parsedId ?? urlOrId.trim();
      final video = await _yt.videos.get(videoId);
      return VideoSource(
        id: video.id.value,
        title: video.title,
        pathOrUrl: video.url,
        type: VideoSourceType.youtube,
        duration: video.duration ?? const Duration(minutes: 5),
        thumbnailUrl: video.thumbnails.highResUrl,
      );
    } catch (e) {
      throw Exception('Gagal mengambil info video YouTube: $e');
    }
  }

  /// Downloads YouTube video stream locally for processing.
  /// Prefers a muxed (video+audio) stream; if none exists it downloads the
  /// best video-only and audio-only streams and merges them with FFmpeg.
  Future<File> downloadVideo(
    String videoIdOrUrl, {
    Function(double progress)? onProgress,
  }) async {
    try {
      final videoId = VideoId.parseVideoId(videoIdOrUrl.trim()) ?? videoIdOrUrl.trim();
      final manifest = await _yt.videos.streamsClient.getManifest(videoId);
      final tempDir = await getTemporaryDirectory();

      if (manifest.muxed.isNotEmpty) {
        final streamInfo = manifest.muxed.withHighestBitrate();
        return _downloadStream(
          streamInfo,
          '${tempDir.path}/yt_$videoId.mp4',
          onProgress,
        );
      }

      if (manifest.videoOnly.isNotEmpty) {
        final videoInfo = manifest.videoOnly.withHighestBitrate();
        final videoFile = await _downloadStream(
          videoInfo,
          '${tempDir.path}/yt_${videoId}_v.mp4',
          onProgress,
        );

        if (manifest.audioOnly.isNotEmpty) {
          final audioInfo = manifest.audioOnly.withHighestBitrate();
          final audioFile = await _downloadStream(
            audioInfo,
            '${tempDir.path}/yt_${videoId}_a.m4a',
            null,
          );

          final mergedFile = File('${tempDir.path}/yt_$videoId.mp4');
          final session = await FFmpegKit.executeWithArguments([
            '-y',
            '-i',
            videoFile.path,
            '-i',
            audioFile.path,
            '-c',
            'copy',
            '-shortest',
            mergedFile.path,
          ]);
          final returnCode = await session.getReturnCode();
          if (ReturnCode.isSuccess(returnCode) &&
              await mergedFile.exists() &&
              (await mergedFile.length()) > 1024) {
            return mergedFile;
          }
        }

        return videoFile;
      }

      throw Exception('Tidak ada stream video yang dapat diunduh');
    } catch (e) {
      throw Exception('Gagal mengunduh video YouTube: $e');
    }
  }

  /// Fetches the video's built-in caption track (subtitle) as word-level
  /// timestamps, reusing YouTube's own transcript instead of running Whisper.
  /// Returns `null` when the video has no usable captions so the caller can
  /// fall back to local transcription.
  Future<List<WhisperWord>?> fetchTranscript(String videoIdOrUrl) async {
    try {
      final videoId = VideoId.parseVideoId(videoIdOrUrl.trim()) ?? videoIdOrUrl.trim();
      final manifest = await _yt.videos.closedCaptions.getManifest(videoId);
      final track = _pickTrack(manifest.tracks);
      if (track == null) return null;

      final captions = await _yt.videos.closedCaptions.get(track);
      return _captionsToWords(captions.captions);
    } catch (e) {
      return null;
    }
  }

  ClosedCaptionTrackInfo? _pickTrack(List<ClosedCaptionTrackInfo> tracks) {
    if (tracks.isEmpty) return null;

    ClosedCaptionTrackInfo? manualFallback;
    for (final track in tracks) {
      final code = track.language.code.toLowerCase();
      if (!track.isAutoGenerated) manualFallback ??= track;
      if (!track.isAutoGenerated &&
          (code == 'id' || code == 'id-id' || code == 'in')) {
        return track;
      }
    }
    for (final track in tracks) {
      final code = track.language.code.toLowerCase();
      if (!track.isAutoGenerated && code == 'en') return track;
    }
    if (manualFallback != null) return manualFallback;
    for (final track in tracks) {
      final code = track.language.code.toLowerCase();
      if (code == 'id' || code == 'id-id' || code == 'in') return track;
    }
    return tracks.first;
  }

  List<WhisperWord> _captionsToWords(List<ClosedCaption> captions) {
    final words = <WhisperWord>[];
    for (final caption in captions) {
      final text = caption.text.trim();
      if (text.isEmpty) continue;

      if (caption.parts.isNotEmpty) {
        for (var i = 0; i < caption.parts.length; i++) {
          final part = caption.parts[i];
          final start = caption.offset + part.offset;
          final nextOffset = i + 1 < caption.parts.length
              ? caption.parts[i + 1].offset
              : caption.duration;
          final delta = nextOffset - part.offset;
          final end = start + (delta.isNegative ? Duration.zero : delta);
          words.add(
            WhisperWord(word: part.text.trim(), start: start, end: end),
          );
        }
      } else {
        words.add(
          WhisperWord(word: text, start: caption.offset, end: caption.end),
        );
      }
    }
    return words;
  }

  Future<File> _downloadStream(
    StreamInfo streamInfo,
    String filePath,
    Function(double progress)? onProgress,
  ) async {
    final stream = _yt.videos.streamsClient.get(streamInfo);
    final file = File(filePath);

    if (await file.exists()) {
      await file.delete();
    }

    final output = file.openWrite();
    final totalBytes = streamInfo.size.totalBytes;
    var downloadedBytes = 0;

    await for (final chunk in stream) {
      downloadedBytes += chunk.length;
      output.add(chunk);
      if (onProgress != null && totalBytes > 0) {
        onProgress(downloadedBytes / totalBytes);
      }
    }

    await output.flush();
    await output.close();

    return file;
  }

  void dispose() {
    _yt.close();
  }
}
